config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  root 'top#index'
  resources :users
  resources :user_sessions, only: %i[new create destroy]

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/industry_master_data.rb
class IndustryMasterData < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login, raise: false

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
      rescue StandardError
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user
      redirect_to root_path, notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: '認証のためのメールを送信しました。メールを確認してください。'
      # TODO: 認証メールの送信
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InterviewCom
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}

  %body
    = yield

app/views/top/index.html.haml
.navbar.navbar-expand-lg.navbar-light.bg-light
  .navbar-brand 面接対策.com
  - if current_user
    = link_to 'ログアウト', logout_path, method: :delete

app/views/user_sessions/new.html.haml
.container
  %h2 Log in

  = form_with model: @user, url: user_sessions_path, local: true do |f|
    .form-group
      = f.label :email
      = f.text_field :email, class: 'form-control'
    .form-group
      = f.label :password
      = f.password_field :password, class: 'form-control'
    = f.submit 'ログイン', class: 'btn btn-primary'

  = link_to 'Googleアカウントでログイン', auth_at_provider_path(provider: :google)

app/views/users/new.html.haml
.container
  %h2 Sign Up

  = form_with model: @user, local: true do |f|
    .form-group
      = f.label :email
      = f.text_field :email, class: 'form-control'
    .form-group
      = f.label :password
      = f.password_field :password, class: 'form-control'
    .form-group
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control'
    = f.submit '登録', class: 'btn btn-primary'

  = link_to 'Googleアカウントで登録', auth_at_provider_path(provider: :google)